// Mocks generated by Mockito 5.4.6 from annotations
// in racs_reader/test/features/cards/application/card_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:racs_reader/features/cards/domain/card.dart' as _i4;
import 'package:racs_reader/features/cards/domain/card_local_repository.dart'
    as _i6;
import 'package:racs_reader/features/cards/domain/card_params.dart' as _i5;
import 'package:racs_reader/features/cards/domain/card_repository.dart' as _i2;
import 'package:racs_reader/features/logger/application/logger_service.dart'
    as _i7;
import 'package:racs_reader/features/logger/domain/log.dart' as _i8;
import 'package:racs_reader/features/logger/domain/log_params.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardRepository extends _i1.Mock implements _i2.CardRepository {
  MockCardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Card?> getCardById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCardById, [id]),
            returnValue: _i3.Future<_i4.Card?>.value(),
          )
          as _i3.Future<_i4.Card?>);

  @override
  _i3.Future<_i4.Card?> getCardByLabel(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getCardByLabel, [name]),
            returnValue: _i3.Future<_i4.Card?>.value(),
          )
          as _i3.Future<_i4.Card?>);

  @override
  _i3.Future<_i4.Card?> getCardByValue(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#getCardByValue, [value]),
            returnValue: _i3.Future<_i4.Card?>.value(),
          )
          as _i3.Future<_i4.Card?>);

  @override
  _i3.Future<List<_i4.Card>> getCards(_i5.CardParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#getCards, [params]),
            returnValue: _i3.Future<List<_i4.Card>>.value(<_i4.Card>[]),
          )
          as _i3.Future<List<_i4.Card>>);

  @override
  _i3.Future<_i4.Card?> markUsed(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markUsed, [id]),
            returnValue: _i3.Future<_i4.Card?>.value(),
          )
          as _i3.Future<_i4.Card?>);
}

/// A class which mocks [CardLocalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardLocalRepository extends _i1.Mock
    implements _i6.CardLocalRepository {
  MockCardLocalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Card?> getCardById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCardById, [id]),
            returnValue: _i3.Future<_i4.Card?>.value(),
          )
          as _i3.Future<_i4.Card?>);

  @override
  _i3.Future<_i4.Card?> getCardByLabel(String? label) =>
      (super.noSuchMethod(
            Invocation.method(#getCardByLabel, [label]),
            returnValue: _i3.Future<_i4.Card?>.value(),
          )
          as _i3.Future<_i4.Card?>);

  @override
  _i3.Future<_i4.Card?> getCardByValue(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#getCardByValue, [value]),
            returnValue: _i3.Future<_i4.Card?>.value(),
          )
          as _i3.Future<_i4.Card?>);

  @override
  _i3.Future<List<_i4.Card>> getCards(_i5.CardParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#getCards, [params]),
            returnValue: _i3.Future<List<_i4.Card>>.value(<_i4.Card>[]),
          )
          as _i3.Future<List<_i4.Card>>);

  @override
  _i3.Future<int> countCards(String? campaignId) =>
      (super.noSuchMethod(
            Invocation.method(#countCards, [campaignId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<_i4.Card?> markUsed(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markUsed, [id]),
            returnValue: _i3.Future<_i4.Card?>.value(),
          )
          as _i3.Future<_i4.Card?>);

  @override
  _i3.Future<void> upsert(_i4.Card? card) =>
      (super.noSuchMethod(
            Invocation.method(#upsert, [card]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> upsertFromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#upsertFromMap, [map]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> upsertAll(List<_i4.Card>? cards) =>
      (super.noSuchMethod(
            Invocation.method(#upsertAll, [cards]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [LoggerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggerService extends _i1.Mock implements _i7.LoggerService {
  MockLoggerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> log(
    String? message, {
    required _i8.LogLevel? level,
    required String? className,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #log,
              [message],
              {#level: level, #className: className},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> debug(String? message, {required String? className}) =>
      (super.noSuchMethod(
            Invocation.method(#debug, [message], {#className: className}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> info(String? message, {required String? className}) =>
      (super.noSuchMethod(
            Invocation.method(#info, [message], {#className: className}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> warning(String? message, {required String? className}) =>
      (super.noSuchMethod(
            Invocation.method(#warning, [message], {#className: className}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> error(String? message, {required String? className}) =>
      (super.noSuchMethod(
            Invocation.method(#error, [message], {#className: className}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.Log>> getLogs(_i9.LogParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#getLogs, [params]),
            returnValue: _i3.Future<List<_i8.Log>>.value(<_i8.Log>[]),
          )
          as _i3.Future<List<_i8.Log>>);

  @override
  _i3.Future<int> countLogs() =>
      (super.noSuchMethod(
            Invocation.method(#countLogs, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> clearLogs() =>
      (super.noSuchMethod(
            Invocation.method(#clearLogs, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
