// Mocks generated by Mockito 5.4.6 from annotations
// in racs_reader/test/features/settings/data/settings_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i2;

import 'package:flutter_webrtc/flutter_webrtc.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:racs_reader/core/network/http_client.dart' as _i6;
import 'package:racs_reader/core/network/webrtc_client.dart' as _i9;
import 'package:racs_reader/core/network/websocket_client.dart' as _i8;
import 'package:racs_reader/core/storage/settings_storage.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHttpClientResponse_0 extends _i1.SmartFake
    implements _i2.HttpClientResponse {
  _FakeHttpClientResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRTCSessionDescription_1 extends _i1.SmartFake
    implements _i3.RTCSessionDescription {
  _FakeRTCSessionDescription_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettingsStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsStorage extends _i1.Mock implements _i4.SettingsStorage {
  MockSettingsStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveThemeMode(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveThemeMode, [value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getThemeMode() =>
      (super.noSuchMethod(
            Invocation.method(#getThemeMode, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> saveHost(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveHost, [value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getHost() =>
      (super.noSuchMethod(
            Invocation.method(#getHost, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> saveCampaignId(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveCampaignId, [value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getCampaignId() =>
      (super.noSuchMethod(
            Invocation.method(#getCampaignId, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);
}

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i6.HttpClient {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> get host =>
      (super.noSuchMethod(
            Invocation.getter(#host),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(this, Invocation.getter(#host)),
            ),
          )
          as _i5.Future<String>);

  @override
  void resetHost() => super.noSuchMethod(
    Invocation.method(#resetHost, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.HttpClientResponse> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParameters: queryParameters},
            ),
            returnValue: _i5.Future<_i2.HttpClientResponse>.value(
              _FakeHttpClientResponse_0(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParameters: queryParameters},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.HttpClientResponse>);

  @override
  _i5.Future<_i2.HttpClientResponse> post(String? path, {Object? body}) =>
      (super.noSuchMethod(
            Invocation.method(#post, [path], {#body: body}),
            returnValue: _i5.Future<_i2.HttpClientResponse>.value(
              _FakeHttpClientResponse_0(
                this,
                Invocation.method(#post, [path], {#body: body}),
              ),
            ),
          )
          as _i5.Future<_i2.HttpClientResponse>);

  @override
  _i5.Future<_i2.HttpClientResponse> put(String? path, {Object? body}) =>
      (super.noSuchMethod(
            Invocation.method(#put, [path], {#body: body}),
            returnValue: _i5.Future<_i2.HttpClientResponse>.value(
              _FakeHttpClientResponse_0(
                this,
                Invocation.method(#put, [path], {#body: body}),
              ),
            ),
          )
          as _i5.Future<_i2.HttpClientResponse>);

  @override
  _i5.Future<_i2.HttpClientResponse> delete(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [path]),
            returnValue: _i5.Future<_i2.HttpClientResponse>.value(
              _FakeHttpClientResponse_0(
                this,
                Invocation.method(#delete, [path]),
              ),
            ),
          )
          as _i5.Future<_i2.HttpClientResponse>);
}

/// A class which mocks [WebSocketClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketClient extends _i1.Mock implements _i8.WebSocketClient {
  MockWebSocketClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<String> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: _i5.Stream<String>.empty(),
          )
          as _i5.Stream<String>);

  @override
  _i5.Stream<bool> get connectionState =>
      (super.noSuchMethod(
            Invocation.getter(#connectionState),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);

  @override
  _i5.Future<String> get host =>
      (super.noSuchMethod(
            Invocation.getter(#host),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(this, Invocation.getter(#host)),
            ),
          )
          as _i5.Future<String>);

  @override
  void resetHost() => super.noSuchMethod(
    Invocation.method(#resetHost, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> connect(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [path]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void send(String? message) => super.noSuchMethod(
    Invocation.method(#send, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [WebRtcClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebRtcClient extends _i1.Mock implements _i9.WebRtcClient {
  MockWebRtcClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<String> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: _i5.Stream<String>.empty(),
          )
          as _i5.Stream<String>);

  @override
  _i5.Stream<_i3.RTCPeerConnectionState> get connectionState =>
      (super.noSuchMethod(
            Invocation.getter(#connectionState),
            returnValue: _i5.Stream<_i3.RTCPeerConnectionState>.empty(),
          )
          as _i5.Stream<_i3.RTCPeerConnectionState>);

  @override
  _i5.Future<_i3.RTCSessionDescription> createOffer() =>
      (super.noSuchMethod(
            Invocation.method(#createOffer, []),
            returnValue: _i5.Future<_i3.RTCSessionDescription>.value(
              _FakeRTCSessionDescription_1(
                this,
                Invocation.method(#createOffer, []),
              ),
            ),
          )
          as _i5.Future<_i3.RTCSessionDescription>);

  @override
  _i5.Future<_i3.RTCSessionDescription> createAnswer(
    _i3.RTCSessionDescription? offer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createAnswer, [offer]),
            returnValue: _i5.Future<_i3.RTCSessionDescription>.value(
              _FakeRTCSessionDescription_1(
                this,
                Invocation.method(#createAnswer, [offer]),
              ),
            ),
          )
          as _i5.Future<_i3.RTCSessionDescription>);

  @override
  _i5.Future<void> setRemoteDescription(
    _i3.RTCSessionDescription? description,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setRemoteDescription, [description]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addIceCandidate(_i3.RTCIceCandidate? candidate) =>
      (super.noSuchMethod(
            Invocation.method(#addIceCandidate, [candidate]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void send(String? message) => super.noSuchMethod(
    Invocation.method(#send, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
