// Mocks generated by Mockito 5.4.6 from annotations
// in racs_reader/test/features/campaigns/application/campaign_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:racs_reader/features/campaigns/domain/campaign.dart' as _i4;
import 'package:racs_reader/features/campaigns/domain/campaign_params.dart'
    as _i5;
import 'package:racs_reader/features/campaigns/domain/campaign_repository.dart'
    as _i2;
import 'package:racs_reader/features/logger/application/logger_service.dart'
    as _i6;
import 'package:racs_reader/features/logger/domain/log.dart' as _i7;
import 'package:racs_reader/features/logger/domain/log_params.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CampaignRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCampaignRepository extends _i1.Mock
    implements _i2.CampaignRepository {
  MockCampaignRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Campaign>> getCampaigns(_i5.CampaignParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#getCampaigns, [params]),
            returnValue: _i3.Future<List<_i4.Campaign>>.value(<_i4.Campaign>[]),
          )
          as _i3.Future<List<_i4.Campaign>>);

  @override
  _i3.Future<int> countCampaigns() =>
      (super.noSuchMethod(
            Invocation.method(#countCampaigns, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}

/// A class which mocks [LoggerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggerService extends _i1.Mock implements _i6.LoggerService {
  MockLoggerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> log(
    String? message, {
    required _i7.LogLevel? level,
    required String? className,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #log,
              [message],
              {#level: level, #className: className},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> debug(String? message, {required String? className}) =>
      (super.noSuchMethod(
            Invocation.method(#debug, [message], {#className: className}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> info(String? message, {required String? className}) =>
      (super.noSuchMethod(
            Invocation.method(#info, [message], {#className: className}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> warning(String? message, {required String? className}) =>
      (super.noSuchMethod(
            Invocation.method(#warning, [message], {#className: className}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> error(String? message, {required String? className}) =>
      (super.noSuchMethod(
            Invocation.method(#error, [message], {#className: className}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.Log>> getLogs(_i8.LogParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#getLogs, [params]),
            returnValue: _i3.Future<List<_i7.Log>>.value(<_i7.Log>[]),
          )
          as _i3.Future<List<_i7.Log>>);

  @override
  _i3.Future<int> countLogs() =>
      (super.noSuchMethod(
            Invocation.method(#countLogs, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> clearLogs() =>
      (super.noSuchMethod(
            Invocation.method(#clearLogs, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
