// Mocks generated by Mockito 5.4.6 from annotations
// in racs_reader/test/features/settings/application/settings_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:racs_reader/features/logger/application/logger_service.dart'
    as _i4;
import 'package:racs_reader/features/logger/domain/log.dart' as _i5;
import 'package:racs_reader/features/logger/domain/log_params.dart' as _i6;
import 'package:racs_reader/features/settings/domain/settings_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i2.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveHost(String? host) =>
      (super.noSuchMethod(
            Invocation.method(#saveHost, [host]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getHost() =>
      (super.noSuchMethod(
            Invocation.method(#getHost, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> saveCampaignId(String? campaignId) =>
      (super.noSuchMethod(
            Invocation.method(#saveCampaignId, [campaignId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getCampaignId() =>
      (super.noSuchMethod(
            Invocation.method(#getCampaignId, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> testHttp() =>
      (super.noSuchMethod(
            Invocation.method(#testHttp, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> testWebSocket() =>
      (super.noSuchMethod(
            Invocation.method(#testWebSocket, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> testStun() =>
      (super.noSuchMethod(
            Invocation.method(#testStun, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [LoggerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggerService extends _i1.Mock implements _i4.LoggerService {
  MockLoggerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> log(
    String? message, {
    required _i5.LogLevel? level,
    required String? className,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #log,
              [message],
              {#level: level, #className: className},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> debug(String? message, {required String? className}) =>
      (super.noSuchMethod(
            Invocation.method(#debug, [message], {#className: className}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> info(String? message, {required String? className}) =>
      (super.noSuchMethod(
            Invocation.method(#info, [message], {#className: className}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> warning(String? message, {required String? className}) =>
      (super.noSuchMethod(
            Invocation.method(#warning, [message], {#className: className}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> error(String? message, {required String? className}) =>
      (super.noSuchMethod(
            Invocation.method(#error, [message], {#className: className}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Log>> getLogs(_i6.LogParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#getLogs, [params]),
            returnValue: _i3.Future<List<_i5.Log>>.value(<_i5.Log>[]),
          )
          as _i3.Future<List<_i5.Log>>);

  @override
  _i3.Future<int> countLogs() =>
      (super.noSuchMethod(
            Invocation.method(#countLogs, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> clearLogs() =>
      (super.noSuchMethod(
            Invocation.method(#clearLogs, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
