// Mocks generated by Mockito 5.4.6 from annotations
// in racs_reader/test/features/campaigns/data/campaign_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:racs_reader/core/network/http_client.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHttpClientResponse_0 extends _i1.SmartFake
    implements _i2.HttpClientResponse {
  _FakeHttpClientResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i3.HttpClient {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> get host =>
      (super.noSuchMethod(
            Invocation.getter(#host),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(this, Invocation.getter(#host)),
            ),
          )
          as _i4.Future<String>);

  @override
  void resetHost() => super.noSuchMethod(
    Invocation.method(#resetHost, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.HttpClientResponse> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParameters: queryParameters},
            ),
            returnValue: _i4.Future<_i2.HttpClientResponse>.value(
              _FakeHttpClientResponse_0(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParameters: queryParameters},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.HttpClientResponse>);

  @override
  _i4.Future<_i2.HttpClientResponse> post(String? path, {Object? body}) =>
      (super.noSuchMethod(
            Invocation.method(#post, [path], {#body: body}),
            returnValue: _i4.Future<_i2.HttpClientResponse>.value(
              _FakeHttpClientResponse_0(
                this,
                Invocation.method(#post, [path], {#body: body}),
              ),
            ),
          )
          as _i4.Future<_i2.HttpClientResponse>);

  @override
  _i4.Future<_i2.HttpClientResponse> put(String? path, {Object? body}) =>
      (super.noSuchMethod(
            Invocation.method(#put, [path], {#body: body}),
            returnValue: _i4.Future<_i2.HttpClientResponse>.value(
              _FakeHttpClientResponse_0(
                this,
                Invocation.method(#put, [path], {#body: body}),
              ),
            ),
          )
          as _i4.Future<_i2.HttpClientResponse>);

  @override
  _i4.Future<_i2.HttpClientResponse> delete(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [path]),
            returnValue: _i4.Future<_i2.HttpClientResponse>.value(
              _FakeHttpClientResponse_0(
                this,
                Invocation.method(#delete, [path]),
              ),
            ),
          )
          as _i4.Future<_i2.HttpClientResponse>);
}
